### ISSUE TITLE
Bug: Dictionary<int, int> Serialize fail

### ISSUE THREAD

**Issue by fredliex** [rikimaru0345/Ceras#41] opened 2019-04-05 09:35 UTC
```
new CerasSerializer().Serialize(new Dictionary<int, int> { [1] = 1 });
```
Exception StackTrace (zh-tw):
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=引動過程的目標傳回例外狀況。
  Source=mscorlib
  StackTrace: 
   於 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   於 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   於 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   於 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   於 System.Activator.CreateInstance(Type type, Object[] args)
   於 Ceras.Resolvers.CollectionFormatterResolver.GetFormatter(Type type)
   於 Ceras.CerasSerializer.GetSpecificFormatter(Type type, TypeMetaData meta)
   於 Ceras.Formatters.ReferenceFormatter`1.GetOrCreateEntry(Type type)
   於 Ceras.Formatters.ReferenceFormatter`1.Serialize(Byte[]& buffer, Int32& offset, T value)
   於 .................

內部例外狀況 1:
ArgumentException: 指定的類型不可以是泛型類型定義。
Arg_ParamName_Name
```

fail on `Marshal.SizeOf(KeyValue<int,int>)` in `ReflectionHelper.IsBlittableType`.
expcetion always happen when key and value are both ValueType.

**Comment by rikimaru0345** [comment] 2019-04-05 12:15
Thanks for reporting! :+1:   I'll take a look asap! :smile:

**Comment by rikimaru0345** [comment] 2019-04-05 13:49
The issue is now fixed in:
https://github.com/rikimaru0345/Ceras/commit/5c56488bcc88bcc0037abc46f5719a9db597fb9f

**Closed** 2019-04-05 13:53 UTC
Labels: bug

**Comment by rikimaru0345** [comment] 2019-04-05 13:59
Package 4.0.38 is released on NuGet now

**Comment by fredliex** [comment] 2019-04-05 15:49
so fast! 👍
