### ISSUE TITLE
Support for read-only properties ?

### ISSUE THREAD

**Issue by Nabile-Rahmani** [rikimaru0345/Ceras#9] opened 2018-12-28 15:09 UTC
Hello,

I wanted to check out the library real quick and scratched my head for a good while, and it turned out it didn't serialise read-only properties.
I did a dirty search and replace to add private setters everywhere to help the library out and it worked !

Would it be possible to modify these read-only properties through reflection by retrieving the backing field somehow ?

**Comment by rikimaru0345** [comment] 2018-12-28 17:02
Hi,

if you add setters to the prop, then it's not readonly anymore, so that's why it works, private setters work as well as you mentioned.

So just so I get it right, you want Ceras to be able to serialize (and desrialize) this: ?
`public string Name { get } = "abc";`

It's true that there is a backing field, but it's not so easy to to do automatically.
The naming might change at any time, someone who's compiling the same exact code with mono, or some older c# compiler, or roslyn, or whatever might get an assembly that internally uses backing fields with a different name.

In the test I just did my compiler decides to name it like that:
https://i.imgur.com/0Ln1ELt.png
but it's not guaranted to be named like that.

Because of that Ceras skips fields marked as `IsInitOnly` or `CompilerGeneratedAttribute`.


But there are some options we could explore...

**Comment by rikimaru0345** [comment] 2018-12-28 17:10
Here are some ideas:
1) Maybe we could allow serialization when the user explicitly asks for the backing field to be included. Like this:
![](https://i.imgur.com/ZzNYJXZ.png)

2) Maybe there could be an additional entry in the `TargetMember` enum which is used in the `MemberConfig` attribute you can put on a class, as well as in the `SerializerConfig.DefaultTargets`.
We could add something like `ReadonlyPropertyBackingFields` to this enum.

Automatically including the backing fields of readonly props seems to be a bit wasteful because most people would not want it (and expect it to be skipped).
Also, if you have readonly properties then maybe you want a few of them serialized, but not all.
But in the rare case that you really want all your readonly props serialized, then you can still either add the MemberConfig attribute, or set the DefaultTargets in the config to globally include all of them.

That should cover all possible cases, what do you think?

**Comment by Nabile-Rahmani** [comment] 2018-12-28 17:44
Correct. Well it's a bummer that the name could vary between compilers/versions, but I would have hoped that the runtime would be able to expose the handle to the backing field in some way.

Idea 2 would be the most handy, as it doesn't require peppering attributes around, as I would be doing placing all the setters anyways.

Now, I can totally live without that feature, and adding setters everywhere is a small price to pay for serialising my complex hierarchy, but it would be nice to keep the intent of the code untouched.

**Comment by rikimaru0345** [comment] 2018-12-28 18:15
Oh, I can totally understand you not wanting to add any "outside" stuff like serialization attributes.

In that case you should be able to manually handle the inclusion using `config.ShouldSerializeMember`.
I'm not sure if it gets called for backing fields / compiler generated members, but I could definitely change it so it always does get called. That'd be option 3.

That'd be another way to handle things globally at a centralized location (where the serializer / config is created), so you'd not have to change anything on your actual classes; and you still get fine-control.

Tbh I think all 3 options shouldn't take much time to implement, so I'll put them on my todo list... :)

**Comment by Nabile-Rahmani** [comment] 2018-12-28 19:07
I did place a breakpoint when I added a delegate to the `ShouldSerializeMember` config when I was troubleshooting my way into the library, but unfortunately it doesn't get called for those members, I eventually figured.

For the record, here's the quick and dirty implementation I'm testing:
![image](https://user-images.githubusercontent.com/15223353/50524652-3e3de180-0ad7-11e9-9ff4-4137e6db3cdf.png)

[(And the full diff)](https://github.com/rikimaru0345/Ceras/files/2715493/diff.txt)

It works wonderfully and is even faster than I would have expected given I'm compressing the data !

Thanks a lot for looking into this and making this amazing library :heart:

**Comment by rikimaru0345** [comment] 2018-12-29 08:40
Hey again.

> Thanks a lot for looking into this and making this amazing library :heart: 
First of all thank you for saying that! It really makes me happy if people find this project useful :)

There are a few things I thought of in the meantime.


### Automatic inclusion of hidden fields
While thinking about how to best make it possible to easily serialize hidden backing fields I realized that this would also include other 'spooky' things. There are many more things that can get compiler generated (hidden) fields. For example calling methods on dynamic objects can generate cached invokers, the enumerator and async-method statemachines, ...

So while in your case all of this doesn't apply, I feel hesitant about adding a way that would globally include fields marked as `CompilerGenerated`.

So right now I added an option `SkipCompilerGeneratedFields` to the serializer config which is true by default.
Turning it off will make it so ShouldSerializeMember will get called for all the compiler generated fields (so you can return ForceInclude if you want).

Further `[field: Include]` will work _regardless_ of whether or not SkipCompilerGeneratedFields is true or false. Simply because that is pretty much the most explicit way to include something.

With those two options (in addition to simply adding {private set;} as you did) I think there are enough ways to handle this for now. Handling those fields in the ShouldSerializeCallback would make it so nobody has to change their classes themselves.


### Actions, Funcs, ...
I was looking over your diff just out of interest and I noticed you have a Action or Func somewhere. I'm not 100% sure if that get's serialized right.

Normally I'd expect that there won't be a problem since Ceras can already correctly serialize `MethodInfo` and the captured variables (if there are any), so it is **supposed** to work since there's no real reason why it wouldn't be possible.

However I didn't try that so far, and I don't have a test case for it!
I'll add that as well and make sure serialization of arbitrary delegates/funcs/actions works as intended.
This also makes me wonder about events and if how they should be serialized...

I'll do some testing regarding that later.

**Comment by rikimaru0345** [comment] 2018-12-29 11:20
Update:
There are some issues with directly serializing `MemberInfo`s (and all the types that inherit from it, so `FieldInfo`, `MethodInfo`, ...). I'm tracking it [in an issue](https://github.com/rikimaru0345/Ceras/issues/10). I have added that to my todo list.


The same issue is preventing `MulticastDelegate`s from being serialize and deserialized correctly.

However serializing Actions, Funcs, and events in general has a large number of problems anyway.
Since delegates almost always have a target, that target is needed, and thus gets dragged into the serialization as well. 

That will very quickly drag in pretty much every object in your program... which is of course pretty problematic to say the least haha. While I'm sure we won't find a general solution (other serializers would have thought of a general solution already), maybe we can find some compromise, or adding a new option or something...

But that's not all, [there are many more issues with the idea of serializing delegates](https://stackoverflow.com/a/49139733/372434).

**Comment by Nabile-Rahmani** [comment] 2018-12-29 12:54
I actually thought for a bit and got scared due to my usage of what you'd call "wrapper" types which got included, and it somehow not breaking the state at all, impacting the performance or bloating the output much. I'll expand on this at the end of this long post.

### Interface member serialisation

While I was checking back on the members being serialised by breakpointing on `ShouldSerializeMember`, I found that the serialiser did not walk through and save members of the underlying type of interface members, which can absolutely be an issue if, for instance, my coprocessor registers have vastly different configurations.
It didn't break outright on my quick testing since not much differs where I'm at in my project.

![image](https://user-images.githubusercontent.com/15223353/50538195-0df45280-0b6c-11e9-8842-8bfbb40a95c5.png)

This `ICoprocessor[] COP` array contains references to both a `SystemControlUnit` coprocessor at index 0 and a `FloatingPointUnit` coprocessor type at index 1, and those contain members (mostly just registers) which need to be serialised in order to keep a consistent state.
As it is, the coprocessors are left in their unmodified state between saves and restores since Ceras doesn't register the members of these types.

### Delegate serialisation

I do have quite a lot of delegates, both in the CPU's read and write system bus, but mostly every single one of the memory map accesses have delegates for reads and writes in the system.

They're usually only set once when initially setting up the system, and the only one that currently changes is when the `CartridgeSwapped` event gets called when the setter for the console's `Cartridge` is hit, which swaps a single memory map entry's read and write delegates that reads and writes to that cartridge reference (or to a safe delegate on null references), though I do not (and nor should anyone) make the cartridge member part of the serialisation process for a state, so it all works out !

### Partial type name support

This shouldn't be noteworthy, but I'm glad you made use of `FullType` when recording type information !
I have a tonne of conflicting names, as for example each interface and processor within my `RealityCoprocessor` have their own `Statuses` flags enum partial type, and it would've been catastrophic if only `Name` were used.
I mention this because I've seen a project out there not supporting partial types, and the results were unusable (that reminds me I should fix it).

![image](https://user-images.githubusercontent.com/15223353/50538469-a096f080-0b70-11e9-809e-c439408553d7.png)

![image](https://user-images.githubusercontent.com/15223353/50538476-b2789380-0b70-11e9-8d14-6967a73c5a3b.png)


### "Wrapper" type serialisation

You can think of them as high-level, friendly representation of properties of an underlying value (a register, or a series of bytes in RAM). They're essentially `BitVector` masking getters/setters. I use three kinds of those types.

The first two are entirely optional as they wrap an array value (a register or a multi-byte value of a member that gets serialised anyways (i.e. the `SystemControlUnit.StatusRegister` wrapper indexes the `SystemControlUnit.Registers[RegisterIndex.Status]` `ulong` value, and the `PeripheralInterface.DeviceState` struct wrapper implicitly casts a 4-byte value in `PeripheralInterface.RAM[DeviceStateOffset]`). I can simply discard those members from serialisation.

The third kind is an actual structure member with a single `BitVector32` field, where each property of this structure will mask this field for their getters/setters.

For all of those cases, the serialiser will keep the actual value, as well as the high-level representation values these properties are sourcing from the actual value.
As long as the wrapper types are well-defined, this doesn't cause issues and simply adds a small overhead (i.e. `BitVector32` is a 4-byte value, and `DeviceState` will have 5 1-byte properties, plus the `BitVector32` field).

**Comment by Nabile-Rahmani** [comment] 2018-12-29 13:58
Re: delegates.

The dangers potentially outweight the usefulness of serialising them, but perhaps there could be some instances where they could work.

An option to enable storing them might be turned on if one would like to have an exact state if and only if it is run on the specific version of the software it has been created (i.e. either as a temporary state stored during the program's runtime, or as a permanent storage that is only supported for the version which created it).

**Comment by rikimaru0345** [comment] 2018-12-29 14:00
Regarding Interface Members:

Oh no, that's definitely not supposed to happen, I think.
Ceras is definitely supposed to explore the real type of each entry in an array, as well as all the members inside that type.

Are you certain that the array is the thing that Ceras is having problems with?
Or does it maybe rather have something to do with the actual classes (FloatingPointUnit)?
Maybe something simple, like the members of that class being private and Ceras being set to only set public members?

Can you make a small repro code? Or copy paste your `FloatingPointUnit` class here along with your setup code for Ceras (like, the SerializerConfig that you're passing to it; _if_ you do that)



Delegate serialization:

Ok, so no problem here, right? Or anything that could be improved?

That reminds me, if your methods are static that's a special case since there is no target.
Which means serializing 'myFunc' in here: ![](https://i.imgur.com/VNT9NRf.png) should work without capturing any unintended other objects. (well, as soon as I've fixed serialization of delegates)

Oh and also, if you ever run into a case where you have to serialize a delegate/Action/Func but you need to prevent the target-object of the delegate from being serialized as well: You can mark the target object as `IExternalRootObject`, and then manually resolve that later! It's pretty easy to do in case you ever have that kind of situation.




Wrapper types:

I'm not sure I'm completely following here. Maybe I'll have to take a look at the code you're working with (assuming there are any issues).

As for the `BitVector32`, there's no built in support for that one in Ceras. If everything works for you then I guess that happens because Ceras is actually serializing those helper properties (that use the bit vector as their backing data). But maybe it would be better to actually make it so Ceras only serializes the BitVector and ignores the properties. (adding an [Include] to the bit vector field, and adding a [MemberConfig(TargetMember.None)] to the class itself, to ensure only the [Include]'d bit vector is actually serialized)

**Comment by Nabile-Rahmani** [comment] 2018-12-29 15:16
### Interface members

I'll provide a solution with the small instructions right below.

I have reduced the area of serialisation down to the CPU itself, where the `COP` array holds the coprocessor type instances in question that aren't getting serialised.

![image](https://user-images.githubusercontent.com/15223353/50539171-089f0400-0b7c-11e9-9f1b-2093bc35a0b1.png)

The `COP` property is privately settable, so it is getting probed by the serialiser, however it doesn't walk the underlying types (I believe only `SystemControlUnit` has a serialisable member, `ulong[] Registers { get; private set; }`).

![image](https://user-images.githubusercontent.com/15223353/50539207-bdd1bc00-0b7c-11e9-8a21-de9e345ba37b.png)

Here, the types are instantiated and set to the array.

I thought it might have been because I didn't expose public parameterless constructors for those types (I don't get an exception for these types), but adding them still doesn't make Ceras go through them.

As a side-note, the `Deserialize` overload that returns a new object raises an exception for delegates with parameters, as the library needs parameterless constructors at the moment, but this is outside my current use-case, and I don't think I even need serialised delegates in the first place.

Though it makes me wonder: the CPU's constructor constructs those coprocessors by passing its own reference, which gets stored as a read-only field. Would the `Deserialize<T>(ref T)` maintain this link, as it seems to require a parameterless constructor at the moment ?

#### Test solution

[DotN64.zip](https://github.com/rikimaru0345/Ceras/files/2716490/DotN64.zip)

* Debug the `DotN64.Desktop` project (with an external terminal, for input) by passing `--debug --no-video` as command-line arguments.
* Insert a breakpoint in `DotN64/Diagnostics/Debugger.cs`, at line 284 (`ShouldSerializeMember` delegate).
* Type `state save` into the program's terminal and press Enter.
* Hit `F5` to cycle through the members getting probed.

Add these watches to see which members are getting probed:
 * `m.MemberInfo`
 * `m.MemberInfo.ReflectedType`

### Delegate types

No problemo, I'm 100% okay on that point.
The Re: post up there could maybe-perhaps be of use to some people, however.

### Wrapper types

It's all fine, I was just describing how lucky it was the serialisation test didn't blow up in million pieces.
I don't think it is even possible to detect this kind of use-case for "wrappers", where only a backing value has to be serialised, and the properties are all hitting on it. That's only on my part to fix (but even then it's negligible) :)

**Comment by rikimaru0345** [comment] 2018-12-29 15:35
Just FYI, I opened an issue to keep track of all this delegate madness: https://github.com/rikimaru0345/Ceras/issues/11

I'll write up a detailed response to your recent posts soon! :)

**Comment by Nabile-Rahmani** [comment] 2018-12-29 18:36
It just dawned on me that I have the exact same dependency configuration (read-only passed in self-reference) in `RealityCoprocessor`, except that the members there are clearly defined in separate properties, instead of being put together in an array of a base type like in the `VR4300`.

![image](https://user-images.githubusercontent.com/15223353/50541191-ca680b80-0ba0-11e9-8317-8ecd3aa696de.png)


The serialiser walks through each of these without issues, so this is very puzzling that it doesn't for the array of interfaces' case.

The read-only fields don't exactly matter so long as the deserialisation doesn't nullify the references from the existing instance I'm applying the state to, which works for the `RealityCoprocessor` as of now !
It's so damn near perfection... I have no idea why it doesn't work for the CPU's coprocessors.

If you replace `nintendo64.CPU` by `nintendo64.RCP` as the `Serialize` parameter (in `DotN64/Diagnostics/Debugger.cs`, line 297) and look at the members being probed by `ShouldSerializeMember` when doing `state save`, you'll see it traverses the whole graph for this object, no problems.

Interestingly, I didn't need to add parameterless constructors for those to be saved. If the deserialisation wouldn't have worked, then I wouldn't have been able to have video output, with the exact resolution due to the `VideoInterface` registers controlling it, but I did, so that means it *does* work.

**Comment by Nabile-Rahmani** [comment] 2018-12-29 19:32
No, thank *you* for helping me debug this ! :)
I feel like I'm kind of shoving my issues onto you, but on the flipside I guess it's a very good stress test at the same time, haha !
 I just *know* it can magically do this, it *already has done it* for the RCP part, the only difference is that hecking weird array/interface thingy :p

**Comment by rikimaru0345** [comment] 2018-12-30 06:42
Quick update:
I just started debugging your project. Starting, debugging and reproducing the error was no problem.
I'm currently checking out what exactly is going wrong.
My initial finding is that there's an `IntPtr` member somewhere, and Ceras does not know how to handle it, so it tries to use the dynamic formatter (that's already wrong, IntPtr should have built-in support), then it checks out what IntPtr is made up of and sees this: `void* m_value;` which reflection reports has having the type `System.Void` haha.

From the looks of it it seems like a very simple bug and straightforward to fix, but you never know, maybe I'll uncover something else.
I'll report back soon.

**Comment by rikimaru0345** [comment] 2018-12-30 07:03
One issue I can see in your code is your type-check.
You've got `excludedTypes` but you're checking with `Contains()`, but no type will ever be of type `IVideoOutput`, instead some types my inherit from it.
Also, I noticed that it's serializing Actions and Funcs, so I've added `typeof(Delegate)` to the excluded types.

So this is what I have now:

![](https://i.imgur.com/HXoPkgW.png)

That excludes the members: ReadySysAD, WriteSysAD

**Comment by rikimaru0345** [comment] 2018-12-30 07:15
Seems to work, I guess. I don't know enough about the code to really judge what is supposed to happen (like what things can possibly be null or so). 

So what I did was `state save`, restart program, `state restore` with a breakpoint on the deserialize, and before letting it deserialize I messed around a bit with the cpu by setting `cpu.CP0.Registers = new ulong[1234];` to clear everything and makes the array the wrong size.

After continuing with the deserialization it seems that ceras has correctly restored the state. cpu.CP0.Registers is now back to, what seems like, the original state: ![](https://i.imgur.com/8ieyNkd.png)

**Comment by Nabile-Rahmani** [comment] 2018-12-30 11:20
As I woke up, it all clicked !

### Read-only reference type member serialisation

Considering pretty much all my read-only properties are reference types, and the fact that the `Deserialize` overload that takes a reference to an existing object does not require instantiating new objects, it means that the deserialiser does not need to access any setters or get any backing fields through reflection !

All it needs to do is use the getter to get the reference and modify the object itself !

Shouldn't it be expected behaviour since reference types are still absolutely mutable despite being read-only members ?

In hindsight it makes sense, as my emulator required the state of these read-only reference types, since when it runs it is able to mutate these read-only members.

### Type checking

For the excluded type list, I initially checked if the type inherited from `IVideoOutput`, but when examining what Ceras passed to me, it looked like I received `IVideoOutput` itself as the type, so I figured I could unify everything into a single array. I'm pretty sure it worked as intended.

![image](https://user-images.githubusercontent.com/15223353/50546663-c9c88700-0c2b-11e9-8aca-dad7731d73bc.png)

I made sure I set the `VideoOutput` reference to an actual type that implements `IVideoOutput` (`Window`) to be sure Ceras doesn't return the underlying type, but I guess it doesn't so long as you don't actually call the getter of that property and check the object type that the property returns, so it works as intended :)

### Delegate exclusion

That is a good thing to keep in mind if I ever need to only synchronise the CPU state itself, but under normal circumstance it correctly pulled the console's RAM which I normally serialise with `serialiser.Serialize(nintendo64)` :)

### FloatingPointUnit

Yes, this one indeed doesn't currently have serialised members (it *ambiguously* accesses the `cpu` for its couple registers), but I'll eventually move the FPU registers off the CPU into the FPU itself so it also has its own serialised state. Sorry about that !

Thank you *so much* for fixing this ! I'll check the new version out !

**Comment by rikimaru0345** [comment] 2018-12-30 12:01
### Read-only reference type member serialisation
Yeah that makes sense, but Ceras being able to overwrite/reuse existing objects is more like a "oh wow that's cool, saves some allocations" feature, than it being the primary intended use case.

Just to be sure, is this just an observation? Or are you asking for it to be possible to make it always assign members even when the "container" itself is readonly?
I mean it would work of course, but what is supposed to happen when the data says "the value in this `object` field should be an instance of type A", and then it inspects the thing and finds an object of type B? (so wrong type, but still possible to be in that field because the field type is `object`)? Or the more obvious case, what if the current value is null?
In those cases Ceras has to assign a new instance.

I could maybe add an option for it to explicitly allow this scenario. It's not too far fetched, and being able to restore state into an existing object-graph seems like something many people would want.
However I can't have it enabled by default as that would be just too confusing.
Also, what would you want Ceras to do in the cases where content of the field is null (or of a mismatching type)? Probably just an exception, right?

### Type checking
Ah yes you're completely right. Ceras passes the field, not the actual object!
However there are two things that caused the misunderstanding.
1. Your field indeed IVideoOutput, and not an implementation type. So that's why it worked. Sometimes people use the concrete type instead of an interface of base-type (in that case, it wouldn't work with a direct comparison)
2. I was thinking about delegates as well, and your callbacks are indeed concrete types like Action and Func, so excluding delegates that way wouldn't have worked. That's why I (wrongly) assumed the same thing being the case with the IVideoOutput.

Glad we cleared that up :)

### Delegate exclusion
But was it actually able to restore the RAM state as well?
If it got pulled into the serialization graph indirectly through some delegate, I'm not sure if Ceras would have been (or currently is) able to even restore that delegate.
Manually saving the RAM is definitely the way to go, but it would be interesting nonetheless to see if it would have worked at all :D

**Comment by Nabile-Rahmani** [comment] 2018-12-30 12:53
### Read-only reference type member serialisation

Yeah, I would like it to keep the members read-only and have the serialiser still serialise them as it could do this without reflection performance penalty for reference types.
Maybe it could fallback to using reflection in those edge cases you mentioned (where the types don't match, null, etc. and it has to assign a new reference).

If the field is null, wouldn't the serialisation mark it as null as well without issues ?

### Delegate exclusion

Yeah, the `Nintendo64` type has the `RAM` property, which the `CPU` unknowingly accesses through `Read/WriteSysAD`. Those delegates are connected to the `RealityCoprocessor`'s memory maps (those have Read/Write delegates too), which for the RAM memory space (in `RDRAMInterface`) will go get the `nintendo64.RAM.Memory` reference.
Talk about indirection ! But it works as intended ! :smile: 

The reason behind this indirection is to allow the `VR4300` CPU to be a completely generic CPU which has no idea it is part of a specific device like the `Nintendo64`.
This decoupling makes it a potentially reusable component as a library, for completely different use-cases.

I don't remember how I found your project as I somehow have a bookmark that dates back to October:
![image](https://user-images.githubusercontent.com/15223353/50547217-3d6f9180-0c36-11e9-817d-d528e431cf3f.png)

But if I had to guess it was probably when I looked for serialisation libraries on NuGet.
Though what made me actually try it out a couple days ago was when I saw it appear in the GitHub dashboard's discover repositories features, which reminded me of its existence :laughing: 
It's my first time using a serialisation library, by the way :p

It's just *perfection* ! :ok_hand:

**Comment by rikimaru0345** [comment] 2018-12-30 15:02
> Yeah, I would like it to keep the members read-only and have the serialiser still serialise them as it could do this without reflection performance penalty for reference types.
Maybe it could fallback to using reflection in those edge cases you mentioned (where the types don't match, null, etc. and it has to assign a new reference).
If the field is null, wouldn't the serialisation mark it as null as well without issues ?

Alright, I've put that on my todo list. It makes sense to have it and there really are valid use cases (such as yours). 

Fallback to reflection will be needed, but as long as the intent behind the feature is made very clear to everyone there are no downsides.

Not sure I understand the last question correctly. You're asking if it would write null to the field if the data says it should be null? If so, yea, that's what would happen, but assigning null is still an assignment so it would have to use reflection for that too. (probably not what you meant... ?)

> By the way, Ceras doesn't need to explicitly support BitVector32, since it has a UInt32 field it serialises:

That only happens because you have set `TargetMembers.All` in your code.
With an explicit formatter it will always work.
Which reminds me: maybe it would be good to have some sort of override list instead, where people could put in types+a member config. For our own types we can add `[MemberConfig]` to customize it, but there's no (easy) way to do it for types from other libraries.
Sure, you could use `ShouldSerializeMember`, or write your own formatter and provide it to the config, but that's pretty uncomfortable. 

> I cannot reproduce the pulling of RAM due to delegate captures when only serialising CPU with either version 1.2.21 or 1.2.23. How did this happen on your end ? Were you perhaps serialising the whole console instead of only the CPU when you noticed this ?

I'm not sure, the only thing I can say for sure is that I was always serializing the cpu, so no changes there.
But maybe it happened because I was working on some other stuff as well at the same time?


> Further, was the VersionTolerance.AutomaticEmbedded not including the SystemControlUnit members supposed to be fixed in version 1.2.23 ? I have to turn versioning off for its members to be captured at the moment.

I'll take a look. Turning version tolerance on or off should not make a difference in what gets serialized, only how things are written (and that schema data is added as well), so something is not right here.

**Comment by rikimaru0345** [comment] 2018-12-30 15:55
I just investigated the problem with version tolerance.
It pretty much only happens when you have an subobject, that is an array of interfaces, in that combination.
Stress testing indeed haha. If it weren't for your project it would have probably taken a while for someone to discover this haha.


> So, in short, in my kind of case the speed would be retained as long as the object type of read-only members doesn't change across versions ? Even then, the worst case scenario could be some old state being loaded slower once, so this sounds like a very acceptable trade-off.

Pretty much, yeah.
But even though reflection has a reputation for being very slow, it's not *that* slow. An assignment using `.SetValue()` takes maybe as long as 50 normal assignments (which themselves take basically no time at all). And we're only dealing with a single reference here. So the difference would be imperceptible. Actually, if it's only a single assignment the difference might not even be measurable at all.

> On re-reading this, it sounds like this would be what the option about using reflection for assigning to read-only members would be choosing.
If the option is disabled, it could throw an exception, is that right ?

Hmm, yes. I don't have a concrete plan for it yet. Initially I was thinking about some extra bool setting, but actually you're right, maybe it would be better to have an enum.

It's a little complicated because there are multiple cases.
- **Off** meaning that readonly fields are completely ignored.
- **Members** meaning that it would record the member-values of the object in the readonly field and set set them back to the recorded value on deserialization. But if there is some sort mismatch, it would throw an exception. That means it would only ever work when the user uses the `ref` deserialization constructor. Or if the data happens to tell us that the field should be null anyway. 
- **ForcedOverwrite** which is like members, but in case of a mismatch it would fix the mismatch "by force" (using reflection and SetValue).

Now as for what a mismatch is:
- The field is currently null, but the data tells us it should not be null
- The field contains an instance of some object, but the data tells us it should be null.
- The field contains an instance, but the data tells us that there should be an instance of a different type inside that field. (Example: the field is like `readonly ISomeInterface MyField;` and it currently contains a  `ImplementationA`, but the data tells us it should be an `ImplementationB`)

Maybe the options as I outlined them above (off, members, forced) make the most sense, no? Or maybe I forgot something...

**Comment by Nabile-Rahmani** [comment] 2018-12-31 08:05
It all sounds good to me !

And I guess delegates will also have this similar optional treatment.

As for the fix, I'm absolutely not in a hurry (I've got many, many, many more stuff to deal with) :p

**Comment by rikimaru0345** [comment] 2018-12-31 10:18
> And I guess delegates will also have this similar optional treatment.

Eventually, yes.
In the next update Ceras will completely ban delegates for now (so you have to [Ignore] them).
That is to prevent many problems and unexpected situations other users might have. Allowing delegates at all in the current state is just not reasonable.

But I plan to allow them later, initially only static targets, and later maybe all types of delegates (assuming I can come up with something to assure that no completely unrelated things will get caught up in the serialization).

**Comment by rikimaru0345** [comment] 2018-12-31 10:43
The fix for the interface array in combination with version tolerance is done.
There might be other edge-cases though, so keep that in mind.

I'll continue with that readonly overwriting feature now I think.


Also, if you want to, add me on discord: `Bloodskilled/Rikimaru#0345` it's a bit faster to discuss things there :)

**Comment by rikimaru0345** [comment] 2019-01-04 14:00
This feature is completed.
It will be present in a new release of Ceras soon :tm:

**Closed by rikimaru0345** 2019-01-04 14:00 UTC
Labels: feature request
